# Generated by Django 5.0.2 on 2024-02-23 20:10

import Utils.slug
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0002_alter_article_created_alter_article_slug_and_more"),
        ("Attempts", "0003_alter_answer_answer_alter_answer_created_and_more"),
        ("Comments", "0002_alter_comment_created_alter_comment_text_and_more"),
        ("Companies", "0002_alter_company_created_alter_company_name_and_more"),
        ("Questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Категория"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=Utils.slug.AutoSlugField(
                populate_from="name", unique=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.TextField(verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="question",
            name="article",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="Articles.article",
                verbose_name="Полный ответ",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="categories",
            field=models.ManyToManyField(
                to="Questions.category", verbose_name="Категорий"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="comments",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Comments.comment",
                verbose_name="Комментарии",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="companies",
            field=models.ManyToManyField(
                to="Companies.company", verbose_name="В компаниях"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="question",
            name="level",
            field=models.CharField(
                choices=[
                    ("JUNIOR", "Junior"),
                    ("MIDDLE", "Middle"),
                    ("SENIOR", "Senior"),
                ],
                default="JUNIOR",
                verbose_name="Для уровня",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="slug",
            field=Utils.slug.AutoSlugField(
                populate_from="title", unique=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("MODERATION", "Модерация"),
                    ("PUBLIC", "Опубликован"),
                    ("DECLINED", "Отклонен"),
                ],
                default="MODERATION",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(unique=True, verbose_name="Текст вопроса"),
        ),
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.CharField(
                db_index=True, max_length=255, unique=True, verbose_name="Заголовок"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="question",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="questionstat",
            name="answers",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Attempts.answer",
                verbose_name="Ответы",
            ),
        ),
        migrations.AlterField(
            model_name="questionstat",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="questionstat",
            name="got_at_interview",
            field=models.PositiveSmallIntegerField(
                verbose_name="Встречался на интервью"
            ),
        ),
        migrations.AlterField(
            model_name="questionstat",
            name="question_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="Questions.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="questionstat",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="questionstat",
            name="views",
            field=models.PositiveSmallIntegerField(verbose_name="Просмотров"),
        ),
    ]
