# Generated by Django 5.0.2 on 2024-02-23 20:10

import Utils.slug
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=Utils.slug.AutoSlugField(
                populate_from="text", unique=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="text",
            field=models.TextField(verbose_name="Полный текст ответа"),
        ),
        migrations.AlterField(
            model_name="article",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
