# Generated by Django 5.0.2 on 2024-02-23 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_initial"),
        ("Questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="question_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Questions.question",
                verbose_name="Вопросы",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="remind_difficult",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Не верно"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="remind_easy",
            field=models.PositiveSmallIntegerField(default=6, verbose_name="Верно"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="remind_in",
            field=models.PositiveSmallIntegerField(
                default=2, verbose_name="Напоминать о тренировках"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="remind_moderate",
            field=models.PositiveSmallIntegerField(
                default=3, verbose_name="Не совсем верно"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="review",
            name="number_of_interview_sessions",
            field=models.PositiveSmallIntegerField(verbose_name="Кол-во сессий"),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(verbose_name="Текст отзыва"),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="review",
            name="user_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
