# Generated by Django 5.0.2 on 2024-02-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("CORRECT", "Верно"),
                            ("WRONG", "Не верно"),
                            ("MODERATE", "Почти верно"),
                        ],
                        default="CORRECT",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время начала"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время завершения"
                    ),
                ),
                ("session_id", models.UUIDField()),
                (
                    "answer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Attempts.answer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия интервью",
                "verbose_name_plural": "Сессии интервью",
            },
        ),
    ]
