# Generated by Django 5.0.2 on 2024-02-23 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Attempts", "0002_initial"),
        ("Questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.CharField(
                choices=[
                    ("CORRECT", "Верно"),
                    ("WRONG", "Не верно"),
                    ("MODERATE", "Почти верно"),
                ],
                default="CORRECT",
                verbose_name="Оценил ответ",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="answer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="Attempts.answer",
                verbose_name="Оценил ответ",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="question_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Questions.question",
                verbose_name="Вопросы",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="session_id",
            field=models.UUIDField(verbose_name="ID-Сессии"),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
